[package]
name = "beginnings"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[build-dependencies]
cc = "1.2.28"

# [build]
# rustc-link-lib = ["shadowing"]
# rustc-link-search = ["."]

[[bin]]
name = "beginnings"
path = "src/main.rs"